# Generated by Django 3.2 on 2023-11-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(blank=True, max_length=150, null=True)),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
                ('view', models.PositiveBigIntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='brand.brand')),
            ],
            options={
                'unique_together': {('name', 'brand')},
            },
        ),
    ]
