# Generated by Django 3.2 on 2023-10-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uqdate_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
