# Generated by Django 3.2 on 2023-11-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='uqdate_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
